#Brewfile
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"

brew "eugenmayer/dockersync/unox"
brew "fping"
brew "fzf"
brew "git"
brew "jid"
brew "jq"
brew "mysql-client"
brew "nmap"
brew "ripgrep"
brew "speedtest-cli"
brew "tmux"
brew "unison"
brew "wireshark"
brew 'bitwarden-cli'

cask "ngrok"
cask "wireshark"
cask "kap"
cask "mactex"
