#!/usr/bin/env bash
#
# Run all dotfiles installers.
# Full credits to https://github.com/holman/dotfiles

set -e

cd "$(dirname $0)"/..

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done
